# Generated by Django 3.1 on 2022-12-11 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default-title', max_length=100)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='NippoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='日付')),
                ('title', models.CharField(default='default-title', max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(default='default-content', verbose_name='内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False, verbose_name='公開する')),
            ],
        ),
    ]
