# Generated by Django 3.1 on 2022-12-16 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='予定日'),
        ),
    ]
