# Generated by Django 3.1 on 2022-12-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='grade',
            field=models.CharField(default='小学生', max_length=100, verbose_name='年齢層：小学生,中学生,高校生,社会人'),
        ),
    ]
