# Generated by Django 3.1 on 2022-12-10 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='nippomodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
        migrations.AddField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(default='slug_maker', max_length=20, unique=True),
        ),
    ]
