# Generated by Django 3.1 on 2022-12-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nippomodel',
            name='public',
        ),
    ]
