# Generated by Django 3.1 on 2022-12-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0002_remove_nippomodel_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nippomodel',
            name='title',
        ),
        migrations.AddField(
            model_name='nippomodel',
            name='district',
            field=models.CharField(default='地区', max_length=100, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='nippomodel',
            name='team',
            field=models.CharField(default='チーム名', max_length=100, verbose_name='チーム名'),
        ),
    ]
