# Generated by Django 3.1 on 2022-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='title',
            field=models.CharField(default='default-title', max_length=100),
        ),
        migrations.AlterField(
            model_name='nippomodel',
            name='content',
            field=models.CharField(default='default-contet', max_length=1000),
        ),
        migrations.AlterField(
            model_name='nippomodel',
            name='title',
            field=models.CharField(default='default-title', max_length=100),
        ),
    ]
