# Generated by Django 3.1 on 2022-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0002_auto_20221211_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='content',
            field=models.TextField(default='default-content', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nippomodel',
            name='title',
            field=models.CharField(default='default-title', max_length=100, verbose_name='タイトル'),
        ),
    ]
