# Generated by Django 3.1 on 2022-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0003_auto_20221209_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='content',
            field=models.TextField(verbose_name='default-contet'),
        ),
    ]
