# Generated by Django 3.1 on 2022-12-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0003_auto_20221211_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nippomodel',
            name='slug',
        ),
    ]
