# Generated by Django 3.1 on 2022-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0004_remove_nippomodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
