# Generated by Django 3.1 on 2022-12-10 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0004_auto_20221209_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
